import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
     'commons/intro',
     'commons/git_intro',
     'commons/git_intro_copy',
     'commons/docusaurus-all-features',
     'commons/master-docs-template',
     'commons/html_notes',
    {
      type: 'category',
      label: 'Docker',
      items: [
        'commons/docs_intro',
      ],
    },
    'commons/uv_intro',
    {
       type: 'category',
      label: 'Alembic',
      items: [
        
        'commons/alembic/alembic_async',
        'commons/alembic/alembic_sync',
      ],

    },
  ],

  Python: [
    {
      type: 'category',
      label: 'Python',
      items: [
        'python/python_intro',
         'python/python_variables',
         'python/python_private_variables',
         'python/python_data_types',
         'python/python_type_casting',  
         'python/python_operators',
         'python/python_comments',
         'python/python_walrus_operator',
         'python/python_control_flow',
         'python/python_data_types',
         
      ],
    },
    {
      type: 'category',
      label: 'Python Functions & Modules',
      items: [
        'python/python_intro',
         'python/python_variables',
      ],
    }
  ],
   FastAPI: [
    {
      type: 'category',
      label: 'Basic - CRUD',
      items: [
        'fastapi/fastapi_basic',
        'fastapi/installation_basic_setup',
        'fastapi/type_hinting',
        'fastapi/decorator',
        'fastapi/fastapi_basic_CRUD',
        
        
      ],
    },
     {
      type: 'category',
      label: 'Pydantic Models',
      items: [
        'python/python_intro',
         'python/python_variables',
      ],
    }
  ],

  SQL: [
    {
      type: 'category',
      label: 'SQL',
      items: [
        'sql/sql_intro',
      ],
    },
  ],

  Docker: [
    {
      type: 'category',
      label: 'Docker',
      items: [
        'docker/docker_intro',
      ],
    },
  ],
};

export default sidebars;

